apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "efk.name" . }}
    chart: {{ template "efk.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  username: {{  .Values.main.es.username | b64enc  }}
  password: {{  .Values.main.es.password | b64enc  }}