apiVersion: v1
kind: Secret
metadata:
  name: elastic-certificates
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "efk.name" . }}
    chart: {{ template "efk.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "certs/elastic-certificates.p12" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}