apiVersion: v1
kind: Secret
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "efk.name" . }}
    chart: {{ template "efk.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  encryptionkey: {{  .Values.main.kibana.encryptionkey | b64enc  }}